// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using VillaCommunityManagement.Data;

#nullable disable

namespace VillaCommunityManagement.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("VillaCommunityManagement.Models.AdminLogin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdminId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("PasswordResetTokenExpiry")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AdminId");

                    b.ToTable("AdminLogin", (string)null);
                });

            modelBuilder.Entity("VillaCommunityManagement.Models.Expenditure", b =>
                {
                    b.Property<int>("ExpenditureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ExpenditureId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("Payment_date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("paid_by")
                        .HasColumnType("text");

                    b.Property<string>("payment_details")
                        .HasColumnType("text");

                    b.HasKey("ExpenditureId");

                    b.ToTable("Expenditure", (string)null);
                });

            modelBuilder.Entity("VillaCommunityManagement.Models.Income", b =>
                {
                    b.Property<int>("IncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IncomeId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Income_Details")
                        .HasColumnType("text");

                    b.Property<string>("income_source")
                        .HasColumnType("text");

                    b.Property<int>("month")
                        .HasColumnType("integer");

                    b.HasKey("IncomeId");

                    b.ToTable("Income", (string)null);
                });

            modelBuilder.Entity("VillaCommunityManagement.Models.Maintenance", b =>
                {
                    b.Property<int>("MaintenanceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MaintenanceId"));

                    b.Property<DateTime>("Due")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<bool>("Payment_details")
                        .HasColumnType("boolean");

                    b.Property<int>("Villa_No")
                        .HasColumnType("integer");

                    b.Property<decimal?>("paid")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("payment_date")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("MaintenanceId");

                    b.ToTable("Maintenance", (string)null);
                });

            modelBuilder.Entity("VillaCommunityManagement.Models.Owner", b =>
                {
                    b.Property<int>("Villa_No")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Villa_No"));

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Owner_name")
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .HasColumnType("text");

                    b.Property<string>("Tenant_name")
                        .HasColumnType("text");

                    b.HasKey("Villa_No");

                    b.ToTable("V_Owners", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
